window.translations = window.translations || {};

window.translations.banderaAzul = {
    es: {
        logo_text: "ADI Caño Negro",
        nav_inicio: "Inicio",
        nav_sobre_adi: "Acerca de Nosotros",
        nav_senderos: "Sendero",
        nav_comunidad: "Comunidad",
        nav_flora: "Flora y Fauna",
        nav_flora_fauna: "Flora y Fauna",
        nav_emprendedores: "Emprendedores",
        nav_bandera: "Bandera Azul Ecológica",
        nav_eventos: "Eventos",

        hero_tag: "Programa AyA · Costa Rica",
        hero_title: "Bandera Azul<br>Ecológica en <span>Caño Negro</span>",
        hero_desc: "Un reconocimiento que impulsa la organización comunitaria hacia la sostenibilidad, la conservación del agua y el cuido del entorno natural que nos rodea.",
        hero_location: "Caño Negro, Los Chiles, Alajuela",

        intro_label: "El programa",
        intro_title: "Un reconocimiento que transforma comunidades",
        intro_subtitle: "Bandera Azul Ecológica es un programa del AyA que busca organizar a la sociedad para mejorar las condiciones ambientales e higiénicas, adaptado a la realidad local.",
        intro_text1: "Nació enfocado en playas y hoy abarca comunidades, centros educativos, espacios naturales protegidos, microcuencas, eventos, hogares sostenibles y construcción sostenible. Cada categoría evalúa aspectos clave como la calidad del agua, manejo de residuos, educación ambiental y eficiencia energética.",
        intro_text2: "Lo que hace especial a este programa es su compromiso anual constante: no es solo una certificación, es un proceso continuo de mejora, aprendizaje y acción colectiva que genera un cambio real en la cultura ambiental de quienes participan.",
        intro_fact1_title: "Múltiples categorías",
        intro_fact1_text: "Comunidades, playas, espacios naturales, hogares sostenibles y más",
        intro_fact2_title: "Renovación anual",
        intro_fact2_text: "La certificación se renueva cada año con nuevas acciones y evaluaciones",
        intro_fact3_title: "Calidad del agua",
        intro_fact3_text: "Eje central junto al manejo de residuos y la educación ambiental",
        intro_fact4_title: "Acción colectiva",
        intro_fact4_text: "Involucra a toda la comunidad en un proceso continuo de mejora",

        logro_label: "Logro destacado",
        logro_title: "Caño Negro con todas las estrellas",
        logro_subtitle: "El Refugio Nacional de Vida Silvestre Mixto Caño Negro obtuvo la Bandera Azul Ecológica en la categoría Espacios Naturales Protegidos con la distinción más alta posible.",
        logro_categoria: "Espacios Naturales Protegidos",
        logro_nombre: "Refugio Nacional de Vida Silvestre Mixto Caño Negro",
        logro_blancas: "5 Estrellas blancas",
        logro_verde: "Estrella verde",
        logro_dorada: "Estrella dorada",
        logro_naranja: "Estrella naranja",
        logro_gris: "Estrella gris",

        stars_label: "¿Qué representa cada una?",
        stars_title: "El significado de cada estrella",
        stars_subtitle: "Cada estrella adicional representa compromisos específicos más allá del puntaje base, reconociendo acciones concretas en distintas áreas de sostenibilidad.",

        star_blanca_title: "5 Estrellas Blancas",
        star_blanca_desc: "Se obtienen por alcanzar una nota superior a 90 puntos en la evaluación general del programa, demostrando un alto nivel de compromiso ambiental.",
        star_verde_title: "Estrella Verde",
        star_verde_desc: "Se otorga por contar con un programa Bandera Azul Ecológica Hogar Sostenible activo dentro de la comunidad.",
        star_verde_nota: "Familia Karen Santamaría Rodríguez",
        star_dorada_title: "Estrella Dorada",
        star_dorada_desc: "Reconoce las acciones concretas realizadas en la protección de cuerpos de agua dentro del área.",
        star_naranja_title: "Estrella Naranja",
        star_naranja_desc: "Reconoce las acciones realizadas en favor del bienestar animal dentro del refugio y su zona de influencia.",
        star_gris_title: "Estrella Gris",
        star_gris_desc: "Se obtiene por la participación activa en el programa Ecoins, que incentiva el reciclaje y la economía circular comunitaria.",

        imp_label: "Impacto real",
        imp_title: "¿Por qué importa este programa?",
        imp_subtitle: "La Bandera Azul Ecológica genera beneficios concretos para las comunidades, el ambiente y el desarrollo sostenible del territorio.",
        imp_card1_title: "Protección de la Salud",
        imp_card1_desc: "Garantiza la calidad sanitaria del agua y los espacios públicos, evitando riesgos para la salud de la comunidad y los visitantes.",
        imp_card2_title: "Sostenibilidad y Conservación",
        imp_card2_desc: "Fomenta la protección de los recursos naturales y la acción climática mediante el trabajo colectivo y organizado.",
        imp_card3_title: "Turismo de Calidad",
        imp_card3_desc: "Posiciona a Caño Negro como un destino seguro y sostenible, atrayendo visitantes conscientes y responsables con el entorno.",
        imp_card4_title: "Educación Ambiental",
        imp_card4_desc: "Impulsa un cambio real de hábitos en las comunidades y centros educativos hacia estilos de vida más ecológicos y conscientes.",
        imp_card5_title: "Reconocimiento",
        imp_card5_desc: "Ofrece un sello de prestigio nacional e internacional que visibiliza el esfuerzo de toda una comunidad comprometida con el medio ambiente.",

        hist_label: "Nuestra participación",
        hist_title: "El camino de Caño Negro",
        hist_text1: "En el 2021, con unión y esfuerzo junto a SINAC, la comunidad de Caño Negro se incorporó al programa generando diversas acciones y controles en la localidad. En el 2022 se logró obtener la primera Bandera Azul Ecológica.",
        hist_text2: "Por falta de integración de más manos voluntarias no se continuó la participación formal, manteniéndose congelada la tramitación. Sin embargo, el trabajo comunitario no se detuvo: recolección de residuos, charlas ambientales e integración de ideas siguen activos entre los pobladores.",
        hist_text3: "El programa generó un cambio significativo en la población al crear conciencia sobre el manejo de residuos sólidos y el uso responsable de los recursos. Esperamos pronto retomar la participación formal y seguir sumando hogares al programa.",

        apoyo_label: "Reconocimiento",
        apoyo_title: "Gracias a quienes hacen posible este logro",
        apoyo_subtitle: "Este reconocimiento es el resultado del esfuerzo conjunto de instituciones, organizaciones y personas de la comunidad que creyeron en el programa.",
        apoyo_1: "Bandera Azul Caño Negro",
        apoyo_2: "Programa Bandera Azul Ecológica (AyA)",
        apoyo_3: "ASADA Los Santos",
        apoyo_4: "Municipalidad de Los Chiles",
        apoyo_5: "Fuerza Pública de Costa Rica",
        apoyo_6: "SINAC",
        apoyo_7: "Parque Nacional Volcán Arenal",
        apoyo_8: "Parque Nacional del Agua Juan Castro Blanco",
        apoyo_9: "Refugio N.V.S. Mixto Bosque Alegre",
        apoyo_10: "Personas y negocios locales de Caño Negro",

        closing_tag: "Caño Negro · Bandera Azul",
        closing_title: "« Sigamos sumando hogares, manos y compromisos »",
        closing_desc: "Agradecemos el esfuerzo de todos y los instamos a seguir trabajando. Si querés unirte al programa Bandera Azul Ecológica Hogar Sostenible, tu participación hace la diferencia.",

        help_title: "¿En qué podemos ayudarte?",
        faq_q1: "🏳️ ¿Qué es la Bandera Azul Ecológica?",
        faq_a1: "Es un programa del AyA que certifica comunidades, espacios naturales y centros educativos comprometidos con la sostenibilidad ambiental.",
        faq_q2: "⭐ ¿Cuántas estrellas tiene Caño Negro?",
        faq_a2: "El Refugio obtuvo todas las estrellas: 5 blancas por nota superior a 90 puntos, más las estrellas verde, dorada, naranja y gris.",
        faq_q3: "🏠 ¿Cómo unirme al Hogar Sostenible?",
        faq_a3: "Podés comunicarte con la ADI Caño Negro para obtener información sobre cómo incorporar tu hogar al programa.",
        faq_q4: "📍 ¿Dónde está Caño Negro?",
        faq_a4: "Se ubica en Los Chiles, Alajuela, Costa Rica, cerca de la frontera con Nicaragua.",
        faq_q5: "🚗 ¿Cómo llegar?",
        faq_a5: "Podés acceder por la Ruta 138 desde Upala o Los Chiles. Usá el botón de ubicación para ver la ruta.",

        chat_tab: "Acerca de Caño Negro",
        footer_links_title: "Enlaces rápidos",
        footer_contact_title: "Contacto",
        footer_social_title: "Síguenos",
        footer_address: "Caño Negro, Los Chiles, Alajuela, Costa Rica",
        footer_about: "Asociación de Desarrollo Integral de Caño Negro, trabajando por la conservación y el desarrollo sostenible de nuestra comunidad.",
        footer_text: "© 2026 ADI Caño Negro - Todos los derechos reservados"
    },

    en: {
        logo_text: "ADI Caño Negro",
        nav_inicio: "Home",
        nav_sobre_adi: "About Us",
        nav_senderos: "Trail",
        nav_comunidad: "Community",
        nav_flora: "Flora & Fauna",
        nav_flora_fauna: "Flora & Fauna",
        nav_emprendedores: "Entrepreneurs",
        nav_bandera: "Blue Ecological Flag",
        nav_eventos: "Events",

        hero_tag: "AyA Program · Costa Rica",
        hero_title: "Blue Ecological<br>Flag in <span>Caño Negro</span>",
        hero_desc: "An award that drives community organization toward sustainability, water conservation, and care for the natural environment that surrounds us.",
        hero_location: "Caño Negro, Los Chiles, Alajuela",

        intro_label: "The program",
        intro_title: "A recognition that transforms communities",
        intro_subtitle: "The Blue Ecological Flag is an AyA program that aims to organize society to improve environmental and hygienic conditions, adapted to local reality.",
        intro_text1: "It started focused on beaches and now encompasses communities, schools, protected natural areas, watersheds, events, sustainable homes, and sustainable construction. Each category evaluates key aspects such as water quality, waste management, environmental education, and energy efficiency.",
        intro_text2: "What makes this program special is its constant annual commitment: it is not just a certification — it is a continuous process of improvement, learning, and collective action that generates real change in the environmental culture of its participants.",
        intro_fact1_title: "Multiple categories",
        intro_fact1_text: "Communities, beaches, natural areas, sustainable homes, and more",
        intro_fact2_title: "Annual renewal",
        intro_fact2_text: "The certification renews each year with new actions and evaluations",
        intro_fact3_title: "Water quality",
        intro_fact3_text: "Core focus alongside waste management and environmental education",
        intro_fact4_title: "Collective action",
        intro_fact4_text: "Involves the entire community in a continuous process of improvement",

        logro_label: "Featured achievement",
        logro_title: "Caño Negro with all the stars",
        logro_subtitle: "The Caño Negro Mixed Wildlife Refuge obtained the Blue Ecological Flag in the Protected Natural Areas category with the highest possible distinction.",
        logro_categoria: "Protected Natural Areas",
        logro_nombre: "Caño Negro Mixed National Wildlife Refuge",
        logro_blancas: "5 White stars",
        logro_verde: "Green star",
        logro_dorada: "Gold star",
        logro_naranja: "Orange star",
        logro_gris: "Gray star",

        stars_label: "What does each one mean?",
        stars_title: "The meaning of each star",
        stars_subtitle: "Each additional star represents specific commitments beyond the base score, recognizing concrete actions in different areas of sustainability.",

        star_blanca_title: "5 White Stars",
        star_blanca_desc: "Awarded for achieving a score above 90 points in the program's general evaluation, demonstrating a high level of environmental commitment.",
        star_verde_title: "Green Star",
        star_verde_desc: "Granted for having an active Blue Ecological Flag Sustainable Home program within the community.",
        star_verde_nota: "Karen Santamaría Rodríguez Family",
        star_dorada_title: "Gold Star",
        star_dorada_desc: "Recognizes concrete actions taken to protect bodies of water within the area.",
        star_naranja_title: "Orange Star",
        star_naranja_desc: "Recognizes actions taken in favor of animal welfare within the refuge and its area of influence.",
        star_gris_title: "Gray Star",
        star_gris_desc: "Awarded for active participation in the Ecoins program, which encourages recycling and community circular economy.",

        imp_label: "Real impact",
        imp_title: "Why does this program matter?",
        imp_subtitle: "The Blue Ecological Flag generates tangible benefits for communities, the environment, and the sustainable development of the territory.",
        imp_card1_title: "Health Protection",
        imp_card1_desc: "Guarantees the sanitary quality of water and public spaces, preventing health risks for the community and visitors.",
        imp_card2_title: "Sustainability and Conservation",
        imp_card2_desc: "Promotes the protection of natural resources and climate action through collective and organized work.",
        imp_card3_title: "Quality Tourism",
        imp_card3_desc: "Positions Caño Negro as a safe and sustainable destination, attracting environmentally conscious and responsible visitors.",
        imp_card4_title: "Environmental Education",
        imp_card4_desc: "Drives a real change in habits in communities and schools toward more ecological and conscious lifestyles.",
        imp_card5_title: "Recognition",
        imp_card5_desc: "Offers a national and international prestige seal that highlights the effort of an entire community committed to the environment.",

        hist_label: "Our participation",
        hist_title: "Caño Negro's journey",
        hist_text1: "In 2021, through unity and effort alongside SINAC, the Caño Negro community joined the program, generating various actions and controls at the local level. In 2022, the first Blue Ecological Flag was obtained.",
        hist_text2: "Due to a lack of integration of more volunteer hands, formal participation was not continued, leaving the process frozen. However, community work did not stop: waste collection, environmental talks, and integration of ideas remain active among residents.",
        hist_text3: "The program generated significant change in the population by raising awareness about solid waste management and responsible use of resources. We hope to soon resume formal participation and continue adding homes to the program.",

        apoyo_label: "Recognition",
        apoyo_title: "Thanks to those who make this achievement possible",
        apoyo_subtitle: "This recognition is the result of the joint effort of institutions, organizations, and community members who believed in the program.",
        apoyo_1: "Bandera Azul Caño Negro",
        apoyo_2: "Blue Ecological Flag Program (AyA)",
        apoyo_3: "ASADA Los Santos",
        apoyo_4: "Municipality of Los Chiles",
        apoyo_5: "Costa Rica Public Force",
        apoyo_6: "SINAC",
        apoyo_7: "Arenal Volcano National Park",
        apoyo_8: "Juan Castro Blanco Water National Park",
        apoyo_9: "Bosque Alegre Mixed N.W.R.",
        apoyo_10: "Local people and businesses of Caño Negro",

        closing_tag: "Caño Negro · Blue Flag",
        closing_title: "“Let's keep adding homes, hands, and commitments”",
        closing_desc: "We are grateful for everyone's effort and encourage you to keep working. If you want to join the Blue Ecological Flag Sustainable Home program, your participation makes a difference.",

        help_title: "How can we help you?",
        faq_q1: "🏳️ What is the Blue Ecological Flag?",
        faq_a1: "It is an AyA program that certifies communities, natural spaces, and schools committed to environmental sustainability.",
        faq_q2: "⭐ How many stars does Caño Negro have?",
        faq_a2: "The Refuge obtained all stars: 5 white for a score above 90 points, plus green, gold, orange, and gray stars.",
        faq_q3: "🏠 How do I join the Sustainable Home program?",
        faq_a3: "You can contact ADI Caño Negro to get information about how to enroll your home in the program.",
        faq_q4: "📍 Where is Caño Negro?",
        faq_a4: "It is located in Los Chiles, Alajuela, Costa Rica, near the border with Nicaragua.",
        faq_q5: "🚗 How do I get there?",
        faq_a5: "You can access it via Route 138 from Upala or Los Chiles. Use the location button to view the route.",

        chat_tab: "About Caño Negro",
        footer_links_title: "Quick links",
        footer_contact_title: "Contact",
        footer_social_title: "Follow us",
        footer_address: "Caño Negro, Los Chiles, Alajuela, Costa Rica",
        footer_about: "Integral Development Association of Caño Negro, working for conservation and sustainable development of our community.",
        footer_text: "© 2026 ADI Caño Negro - All rights reserved"
    },

    fr: {
        logo_text: "ADI Caño Negro",
        nav_inicio: "Accueil",
        nav_sobre_adi: "À propos de nous",
        nav_senderos: "Sentier",
        nav_comunidad: "Communauté",
        nav_flora: "Flore et Faune",
        nav_flora_fauna: "Flore et Faune",
        nav_emprendedores: "Entrepreneurs",
        nav_bandera: "Drapeau Bleu Écologique",
        nav_eventos: "Événements",

        hero_tag: "Programme AyA · Costa Rica",
        hero_title: "Drapeau Bleu<br>Écologique à <span>Caño Negro</span>",
        hero_desc: "Une distinction qui encourage l'organisation communautaire vers la durabilité, la conservation de l'eau et le soin de l'environnement naturel qui nous entoure.",
        hero_location: "Caño Negro, Los Chiles, Alajuela",

        intro_label: "Le programme",
        intro_title: "Une distinction qui transforme les communautés",
        intro_subtitle: "Le Drapeau Bleu Écologique est un programme de l'AyA qui cherche à organiser la société pour améliorer les conditions environnementales et hygiéniques, adapté à la réalité locale.",
        intro_text1: "Né autour des plages, il couvre aujourd'hui les communautés, les établissements scolaires, les espaces naturels protégés, les bassins versants, les événements, les foyers durables et la construction durable. Chaque catégorie évalue des aspects clés tels que la qualité de l'eau, la gestion des déchets, l'éducation environnementale et l'efficacité énergétique.",
        intro_text2: "Ce qui rend ce programme spécial, c'est son engagement annuel constant : il ne s'agit pas seulement d'une certification, mais d'un processus continu d'amélioration, d'apprentissage et d'action collective qui génère un vrai changement dans la culture environnementale de ses participants.",
        intro_fact1_title: "Catégories multiples",
        intro_fact1_text: "Communautés, plages, espaces naturels, foyers durables et plus",
        intro_fact2_title: "Renouvellement annuel",
        intro_fact2_text: "La certification se renouvelle chaque année avec de nouvelles actions et évaluations",
        intro_fact3_title: "Qualité de l'eau",
        intro_fact3_text: "Axe central avec la gestion des déchets et l'éducation environnementale",
        intro_fact4_title: "Action collective",
        intro_fact4_text: "Implique toute la communauté dans un processus continu d'amélioration",

        logro_label: "Réalisation remarquable",
        logro_title: "Caño Negro avec toutes les étoiles",
        logro_subtitle: "Le Refuge National de Vie Sauvage Mixte de Caño Negro a obtenu le Drapeau Bleu Écologique dans la catégorie Espaces Naturels Protégés avec la distinction la plus élevée possible.",
        logro_categoria: "Espaces Naturels Protégés",
        logro_nombre: "Refuge National de Vie Sauvage Mixte Caño Negro",
        logro_blancas: "5 Étoiles blanches",
        logro_verde: "Étoile verte",
        logro_dorada: "Étoile dorée",
        logro_naranja: "Étoile orange",
        logro_gris: "Étoile grise",

        stars_label: "Que représente chacune ?",
        stars_title: "La signification de chaque étoile",
        stars_subtitle: "Chaque étoile supplémentaire représente des engagements spécifiques au-delà du score de base, reconnaissant des actions concrètes dans différents domaines de durabilité.",

        star_blanca_title: "5 Étoiles Blanches",
        star_blanca_desc: "Obtenues en atteignant une note supérieure à 90 points dans l'évaluation générale du programme, démontrant un niveau élevé d'engagement environnemental.",
        star_verde_title: "Étoile Verte",
        star_verde_desc: "Accordée pour avoir un programme Drapeau Bleu Écologique Foyer Durable actif au sein de la communauté.",
        star_verde_nota: "Famille Karen Santamaría Rodríguez",
        star_dorada_title: "Étoile Dorée",
        star_dorada_desc: "Reconnaît les actions concrètes entreprises pour la protection des masses d'eau dans la zone.",
        star_naranja_title: "Étoile Orange",
        star_naranja_desc: "Reconnaît les actions menées en faveur du bien-être animal au sein du refuge et de sa zone d'influence.",
        star_gris_title: "Étoile Grise",
        star_gris_desc: "Obtenue par la participation active au programme Ecoins, qui encourage le recyclage et l'économie circulaire communautaire.",

        imp_label: "Impact réel",
        imp_title: "Pourquoi ce programme est-il important ?",
        imp_subtitle: "Le Drapeau Bleu Écologique génère des bénéfices concrets pour les communautés, l'environnement et le développement durable du territoire.",
        imp_card1_title: "Protection de la Santé",
        imp_card1_desc: "Garantit la qualité sanitaire de l'eau et des espaces publics, évitant les risques pour la santé de la communauté et des visiteurs.",
        imp_card2_title: "Durabilité et Conservation",
        imp_card2_desc: "Favorise la protection des ressources naturelles et l'action climatique grâce au travail collectif et organisé.",
        imp_card3_title: "Tourisme de Qualité",
        imp_card3_desc: "Positionne Caño Negro comme une destination sûre et durable, attirant des visiteurs responsables et conscients de l'environnement.",
        imp_card4_title: "Éducation Environnementale",
        imp_card4_desc: "Impulse un vrai changement de comportements dans les communautés et les écoles vers des modes de vie plus écologiques et conscients.",
        imp_card5_title: "Reconnaissance",
        imp_card5_desc: "Offre un label de prestige national et international qui met en valeur l'effort de toute une communauté engagée pour l'environnement.",

        hist_label: "Notre participation",
        hist_title: "Le parcours de Caño Negro",
        hist_text1: "En 2021, avec unité et effort aux côtés de SINAC, la communauté de Caño Negro a rejoint le programme, générant diverses actions et contrôles au niveau local. En 2022, le premier Drapeau Bleu Écologique a été obtenu.",
        hist_text2: "Faute d'intégration de davantage de bénévoles, la participation formelle n'a pas été poursuivie, laissant la démarche suspendue. Cependant, le travail communautaire ne s'est pas arrêté : collecte de déchets, conférences environnementales et intégration d'idées restent actifs parmi les habitants.",
        hist_text3: "Le programme a généré un changement significatif dans la population en sensibilisant à la gestion des déchets solides et à l'utilisation responsable des ressources. Nous espérons bientôt reprendre la participation formelle et continuer à intégrer des foyers au programme.",

        apoyo_label: "Reconnaissance",
        apoyo_title: "Merci à ceux qui rendent cette réussite possible",
        apoyo_subtitle: "Cette distinction est le résultat de l'effort conjoint d'institutions, d'organisations et de membres de la communauté qui ont cru en ce programme.",
        apoyo_1: "Bandera Azul Caño Negro",
        apoyo_2: "Programme Drapeau Bleu Écologique (AyA)",
        apoyo_3: "ASADA Los Santos",
        apoyo_4: "Municipalité de Los Chiles",
        apoyo_5: "Force Publique du Costa Rica",
        apoyo_6: "SINAC",
        apoyo_7: "Parc National du Volcan Arenal",
        apoyo_8: "Parc National de l'Eau Juan Castro Blanco",
        apoyo_9: "Refuge N.V.S. Mixte Bosque Alegre",
        apoyo_10: "Personnes et commerces locaux de Caño Negro",

        closing_tag: "Caño Negro · Drapeau Bleu",
        closing_title: "« Continuons à ajouter des foyers, des mains et des engagements »",
        closing_desc: "Nous remercions les efforts de tous et vous encourageons à continuer. Si vous souhaitez rejoindre le programme Drapeau Bleu Écologique Foyer Durable, votre participation fait la différence.",

        help_title: "Comment pouvons-nous vous aider ?",
        faq_q1: "🏳️ Qu'est-ce que le Drapeau Bleu Écologique ?",
        faq_a1: "C'est un programme de l'AyA qui certifie les communautés, espaces naturels et écoles engagés dans la durabilité environnementale.",
        faq_q2: "⭐ Combien d'étoiles a Caño Negro ?",
        faq_a2: "Le Refuge a obtenu toutes les étoiles : 5 blanches pour une note supérieure à 90 points, plus les étoiles verte, dorée, orange et grise.",
        faq_q3: "🏠 Comment rejoindre le programme Foyer Durable ?",
        faq_a3: "Vous pouvez contacter l'ADI Caño Negro pour obtenir des informations sur la façon d'inscrire votre foyer au programme.",
        faq_q4: "📍 Où se trouve Caño Negro ?",
        faq_a4: "Il se situe à Los Chiles, Alajuela, Costa Rica, près de la frontière avec le Nicaragua.",
        faq_q5: "🚗 Comment y accéder ?",
        faq_a5: "Vous pouvez y accéder par la Route 138 depuis Upala ou Los Chiles. Utilisez le bouton de localisation pour voir l'itinéraire.",

        chat_tab: "À propos de Caño Negro",
        footer_links_title: "Liens rapides",
        footer_contact_title: "Contact",
        footer_social_title: "Suivez-nous",
        footer_address: "Caño Negro, Los Chiles, Alajuela, Costa Rica",
        footer_about: "Association de Développement Intégral de Caño Negro, travaillant pour la conservation et le développement durable de notre communauté.",
        footer_text: "© 2026 ADI Caño Negro - Tous droits réservés"
    }
};
