window.translations = window.translations || {};

window.translations.sobreADI = {
    es: {
        logo_text: "ADI Caño Negro",
        nav_inicio: "Inicio",
        nav_sobre_adi: "Acerca de Nosotros",
        nav_senderos: "Sendero",
        nav_comunidad: "Comunidad",
        nav_flora_fauna: "Flora y Fauna",
        nav_emprendedores: "Emprendedores",
        nav_bandera: "Bandera Azul Ecológica",

        hero_tag: "Comunidad · Turismo · Desarrollo Integral",
        hero_title: "Construyendo juntos el <span>futuro de Caño Negro</span>",
        hero_desc: "Trabajamos junto a la comunidad para impulsar el desarrollo turístico, deportivo y comunitario de Caño Negro.",
        hero_location: "Caño Negro, Los Chiles, Alajuela",

        quienes_label: "Nuestra organización",
        quienes_title: "¿Quiénes somos?",
        quienes_subtitle: "Somos una asociación comunitaria que impulsa el desarrollo de Caño Negro junto a instituciones, organizaciones y personas voluntarias.",
        quienes_text1: "La Asociación de Desarrollo Integral de Caño Negro trabaja junto a la comunidad para impulsar iniciativas que contribuyan al desarrollo y bienestar de sus habitantes.",
        quienes_text2: "A través de la colaboración con instituciones, organizaciones, universidades y otros aliados, la ADI participa en proyectos relacionados con turismo, infraestructura, deporte, seguridad y participación comunitaria.",
        quienes_text3: "Entre las iniciativas desarrolladas destaca el Manakin Eco-Trail, así como diferentes acciones de mantenimiento y mejoramiento de espacios comunitarios.",
        quienes_photo_credit: "Foto: Paraíso Tropical Caño Negro",
        quienes_sloth_caption: "Perezoso de tres dedos (<em>Bradypus variegatus</em>)",

        quienes_fact1_title: "Desarrollo comunitario",
        quienes_fact1_text: "Iniciativas y acciones en beneficio directo de la comunidad de Caño Negro.",
        quienes_fact2_title: "Turismo",
        quienes_fact2_text: "Impulso de proyectos turísticos como el Manakin Eco-Trail.",
        quienes_fact3_title: "Infraestructura",
        quienes_fact3_text: "Mantenimiento y mejoras en espacios e infraestructura comunitaria.",
        quienes_fact4_title: "Deporte",
        quienes_fact4_text: "Apoyo a espacios y proyectos relacionados con el deporte y la recreación.",
        quienes_fact5_title: "Participación ciudadana",
        quienes_fact5_text: "Voluntariado y espacios de participación para vecinos y vecinas.",
        quienes_fact6_title: "Trabajo colaborativo",
        quienes_fact6_text: "Alianzas con instituciones, universidades, organizaciones y empresas.",

        vol_label: "Voluntariado",
        vol_title: "Sé parte del cambio",
        vol_subtitle: "La participación de las personas de la comunidad es clave para desarrollar actividades e iniciativas. Estas son algunas de las formas en que la comunidad se ha involucrado.",

        vol_card1_title: "Charity CR",
        vol_card1_desc: "Actividades para niños y familias de la comunidad, realizadas junto a Charity CR.",
        vol_card2_title: "Jornadas de limpieza",
        vol_card2_desc: "Limpieza del Parque y del Campo Ferial junto a personas voluntarias de la comunidad.",
        vol_card3_title: "Colaboración con organizaciones",
        vol_card3_desc: "Trabajo conjunto con diferentes organizaciones e instituciones en beneficio de Caño Negro.",
        vol_card4_title: "Participación comunitaria",
        vol_card4_desc: "Participación en actividades, capacitaciones e iniciativas relacionadas con proyectos comunitarios.",

        vol_note: "Dentro del plan de trabajo se contempla el desarrollo de un Programa de Voluntariado para fortalecer la participación comunitaria.",

        proy_label: "Nuestro trabajo",
        proy_title: "Lo que hemos construido",
        proy_subtitle: "Estas son algunas de las acciones que hemos desarrollado junto a la comunidad, instituciones y organizaciones aliadas.",

        proy1_title: "Manakin Eco-Trail",
        proy1_desc: "Desarrollo de una iniciativa turística junto a instituciones, organizaciones y universidades, con trabajo en el sendero y el Centro de Desarrollo Turístico y Empresarial.",
        proy2_title: "Mejoramiento de espacios comunitarios",
        proy2_desc: "Mantenimiento, limpieza, seguridad y mejoras de infraestructura en diferentes espacios de la comunidad.",
        proy3_title: "Campo Ferial",
        proy3_desc: "Trabajos de mantenimiento y mejoramiento del Campo Ferial.",
        proy4_title: "Infraestructura",
        proy4_desc: "Mejoras relacionadas con electricidad, tuberías y diferentes espacios comunitarios del sendero.",
        proy5_title: "Seguridad comunitaria",
        proy5_desc: "Trabajo conjunto con Fuerza Pública y desarrollo de Mesas de Seguridad.",
        proy6_title: "Alianzas y colaboración",
        proy6_desc: "Trabajo conjunto con universidades, instituciones, organizaciones y empresas aliadas.",

        badge_completado: "Completado",
        badge_proyectado: "Proyectado",

        futuro_label: "Hacia el futuro",
        futuro_title: "Seguimos construyendo",
        futuro_subtitle: "El Plan de Trabajo contempla nuevas iniciativas para continuar impulsando el desarrollo de Caño Negro.",

        fut1_title: "Turismo y desarrollo",
        fut1_item1: "Desarrollo de proyectos turísticos.",
        fut1_item2: "Centro de Formación Turística y Empresarial.",
        fut1_item3: "Fortalecimiento de espacios relacionados con el turismo.",

        fut2_title: "Deporte y recreación",
        fut2_item1: "Mejoramiento de la Plaza de Fútbol: camerinos, cerramiento y graderías.",
        fut2_item2: "Construcción de un espacio multiusos para deportes.",
        fut2_item3: "Mejoramiento de espacios deportivos y recreativos.",

        fut3_title: "Infraestructura comunitaria",
        fut3_item1: "Remodelación y equipamiento del salón comunal.",
        fut3_item2: "Mantenimiento y construcción de obras comunales.",
        fut3_item3: "Construcción y equipamiento de una cocina comunal.",
        fut3_item4: "Mejoras en la red vial cantonal y alcantarillado.",

        fut4_title: "Equipamiento y recursos",
        fut4_item1: "Herramientas y equipo.",
        fut4_item2: "Equipo tecnológico y de sonido.",
        fut4_item3: "Suministros, equipo y mobiliario de oficina.",
        fut4_item4: "Equipo de primeros auxilios y elementos de seguridad.",

        fut5_title: "Participación comunitaria",
        fut5_item1: "Programa de Voluntariado.",
        fut5_item2: "Reuniones y capacitaciones.",
        fut5_item3: "Actividades de participación y colaboración comunitaria.",

        closing_tag: "ADI Caño Negro",
        closing_title: "\"Cuando una comunidad trabaja unida, no solo construye proyectos, construye futuro.\"",
        closing_desc: "Ya seas vecino, visitante o aliado institucional, hay un lugar para vos en los proyectos de la ADI Caño Negro.",

        help_title: "¿En qué podemos ayudarte?",

        faq_q1: "🤝 ¿Qué es la ADI Caño Negro?",
        faq_a1: "Es la Asociación de Desarrollo Integral de Caño Negro, una organización comunitaria sin fines de lucro.",
        faq_q2: "🙋 ¿Cómo puedo ser voluntario?",
        faq_a2: "Podés escribirnos por WhatsApp o correo y te contamos las formas activas de participar.",
        faq_q3: "📅 ¿Cuándo se reúne la ADI?",
        faq_a3: "Las reuniones y actividades se coordinan según cada proyecto; contactanos para más información.",
        faq_q4: "📍 ¿Dónde está Caño Negro?",
        faq_a4: "Se ubica en Los Chiles, Alajuela, Costa Rica, cerca de la frontera con Nicaragua.",
        faq_q5: "🚗 ¿Cómo llegar?",
        faq_a5: "Podés acceder por la Ruta 138 desde Upala o Los Chiles. Usá el botón de ubicación para ver la ruta.",

        chat_tab: "Acerca de Caño Negro",

        footer_about: "Asociación de Desarrollo Integral de Caño Negro, trabajando junto a la comunidad por el desarrollo turístico, deportivo, empresarial y comunitario.",
        footer_links_title: "Enlaces rápidos",
        footer_contact_title: "Contacto",
        footer_address: "Caño Negro, Los Chiles, Alajuela, Costa Rica",
        footer_social_title: "Síguenos",
        footer_text: "© 2026 ADI Caño Negro - Todos los derechos reservados"
    },

    en: {
        logo_text: "ADI Caño Negro",
        nav_inicio: "Home",
        nav_sobre_adi: "About Us",
        nav_senderos: "Trail",
        nav_comunidad: "Community",
        nav_flora_fauna: "Flora & Fauna",
        nav_emprendedores: "Entrepreneurs",
        nav_bandera: "Blue Ecological Flag",

        hero_tag: "Community · Tourism · Integral Development",
        hero_title: "Building the <span>future of Caño Negro together</span>",
        hero_desc: "We work alongside the community to drive the tourism, sports, and community development of Caño Negro.",
        hero_location: "Caño Negro, Los Chiles, Alajuela",

        quienes_label: "Our organization",
        quienes_title: "Who we are",
        quienes_subtitle: "We are a community association that drives the development of Caño Negro alongside institutions, organizations, and volunteers.",
        quienes_text1: "The Caño Negro Integral Development Association works alongside the community to drive initiatives that contribute to the development and well-being of its residents.",
        quienes_text2: "Through collaboration with institutions, organizations, universities, and other partners, ADI takes part in projects related to tourism, infrastructure, sports, security, and community participation.",
        quienes_text3: "Among the initiatives carried out, the Manakin Eco-Trail stands out, along with various maintenance and improvement actions in community spaces.",
        quienes_photo_credit: "Photo: Paraíso Tropical Caño Negro",
        quienes_sloth_caption: "Brown-throated three-toed sloth (<em>Bradypus variegatus</em>)",

        quienes_fact1_title: "Community development",
        quienes_fact1_text: "Initiatives and actions that directly benefit the Caño Negro community.",
        quienes_fact2_title: "Tourism",
        quienes_fact2_text: "Driving tourism projects such as the Manakin Eco-Trail.",
        quienes_fact3_title: "Infrastructure",
        quienes_fact3_text: "Maintenance and improvements to community spaces and infrastructure.",
        quienes_fact4_title: "Sports",
        quienes_fact4_text: "Support for spaces and projects related to sports and recreation.",
        quienes_fact5_title: "Civic participation",
        quienes_fact5_text: "Volunteering and participation spaces for neighbors.",
        quienes_fact6_title: "Collaborative work",
        quienes_fact6_text: "Partnerships with institutions, universities, organizations, and businesses.",

        vol_label: "Volunteering",
        vol_title: "Be part of the change",
        vol_subtitle: "Community participation is key to developing activities and initiatives. Here are some of the ways the community has gotten involved.",

        vol_card1_title: "Charity CR",
        vol_card1_desc: "Activities for children and families in the community, carried out together with Charity CR.",
        vol_card2_title: "Cleanup days",
        vol_card2_desc: "Cleanup of the Park and the Fairground alongside community volunteers.",
        vol_card3_title: "Collaboration with organizations",
        vol_card3_desc: "Joint work with different organizations and institutions for the benefit of Caño Negro.",
        vol_card4_title: "Community participation",
        vol_card4_desc: "Participation in activities, training sessions, and initiatives related to community projects.",

        vol_note: "The work plan includes the development of a Volunteer Program to strengthen community participation.",

        proy_label: "Our work",
        proy_title: "What we have built",
        proy_subtitle: "These are some of the actions we have carried out alongside the community, institutions, and partner organizations.",

        proy1_title: "Manakin Eco-Trail",
        proy1_desc: "Development of a tourism initiative alongside institutions, organizations, and universities, including work on the trail and the Tourism and Business Development Center.",
        proy2_title: "Improvement of community spaces",
        proy2_desc: "Maintenance, cleaning, security, and infrastructure improvements in different community spaces.",
        proy3_title: "Fairground",
        proy3_desc: "Maintenance and improvement work at the Fairground.",
        proy4_title: "Infrastructure",
        proy4_desc: "Improvements related to electricity, plumbing, and different community areas along the trail.",
        proy5_title: "Community security",
        proy5_desc: "Joint work with the Public Force and the development of Security Roundtables.",
        proy6_title: "Partnerships and collaboration",
        proy6_desc: "Joint work with universities, institutions, organizations, and partner businesses.",

        badge_completado: "Completed",
        badge_proyectado: "Planned",

        futuro_label: "Looking ahead",
        futuro_title: "We keep building",
        futuro_subtitle: "The Work Plan includes new initiatives to continue driving the development of Caño Negro.",

        fut1_title: "Tourism and development",
        fut1_item1: "Development of tourism projects.",
        fut1_item2: "Tourism and Business Training Center.",
        fut1_item3: "Strengthening of spaces related to tourism.",

        fut2_title: "Sports and recreation",
        fut2_item1: "Improvement of the Soccer Field: locker rooms, fencing, and bleachers.",
        fut2_item2: "Construction of a multi-use space for sports.",
        fut2_item3: "Improvement of sports and recreational spaces.",

        fut3_title: "Community infrastructure",
        fut3_item1: "Remodeling and equipping of the community hall.",
        fut3_item2: "Maintenance and construction of community facilities.",
        fut3_item3: "Construction and equipping of a community kitchen.",
        fut3_item4: "Improvements to the cantonal road network and drainage system.",

        fut4_title: "Equipment and resources",
        fut4_item1: "Tools and equipment.",
        fut4_item2: "Technology and sound equipment.",
        fut4_item3: "Supplies, equipment, and office furniture.",
        fut4_item4: "First-aid equipment and safety items.",

        fut5_title: "Community participation",
        fut5_item1: "Volunteer Program.",
        fut5_item2: "Meetings and training sessions.",
        fut5_item3: "Community participation and collaboration activities.",

        closing_tag: "ADI Caño Negro",
        closing_title: "\"When a community works together, it doesn't just build projects, it builds a future.\"",
        closing_desc: "Whether you're a neighbor, a visitor, or an institutional partner, there's a place for you in ADI Caño Negro's projects.",

        help_title: "How can we help you?",

        faq_q1: "🤝 What is ADI Caño Negro?",
        faq_a1: "It is the Caño Negro Integral Development Association, a nonprofit community organization.",
        faq_q2: "🙋 How can I volunteer?",
        faq_a2: "You can write to us on WhatsApp or by email and we'll tell you the current ways to get involved.",
        faq_q3: "📅 When does ADI meet?",
        faq_a3: "Meetings and activities are coordinated per project; contact us for more information.",
        faq_q4: "📍 Where is Caño Negro located?",
        faq_a4: "It is located in Los Chiles, Alajuela, Costa Rica, near the border with Nicaragua.",
        faq_q5: "🚗 How do I get there?",
        faq_a5: "You can access it via Route 138 from Upala or Los Chiles. Use the location button to see the route.",

        chat_tab: "About Caño Negro",

        footer_about: "Caño Negro Integral Development Association, working alongside the community for tourism, sports, business, and community development.",
        footer_links_title: "Quick links",
        footer_contact_title: "Contact",
        footer_address: "Caño Negro, Los Chiles, Alajuela, Costa Rica",
        footer_social_title: "Follow us",
        footer_text: "© 2026 ADI Caño Negro - All rights reserved"
    },

    fr: {
        logo_text: "ADI Caño Negro",
        nav_inicio: "Accueil",
        nav_sobre_adi: "À propos de nous",
        nav_senderos: "Sentier",
        nav_comunidad: "Communauté",
        nav_flora_fauna: "Flore et Faune",
        nav_emprendedores: "Entrepreneurs",
        nav_bandera: "Pavillon Bleu Écologique",

        hero_tag: "Communauté · Tourisme · Développement Intégral",
        hero_title: "Construire ensemble l'<span>avenir de Caño Negro</span>",
        hero_desc: "Nous travaillons aux côtés de la communauté pour promouvoir le développement touristique, sportif et communautaire de Caño Negro.",
        hero_location: "Caño Negro, Los Chiles, Alajuela",

        quienes_label: "Notre organisation",
        quienes_title: "Qui sommes-nous ?",
        quienes_subtitle: "Nous sommes une association communautaire qui favorise le développement de Caño Negro aux côtés d'institutions, d'organisations et de bénévoles.",
        quienes_text1: "L'Association de Développement Intégral de Caño Negro travaille aux côtés de la communauté pour promouvoir des initiatives contribuant au développement et au bien-être de ses habitants.",
        quienes_text2: "Grâce à la collaboration avec des institutions, des organisations, des universités et d'autres partenaires, l'ADI participe à des projets liés au tourisme, aux infrastructures, au sport, à la sécurité et à la participation communautaire.",
        quienes_text3: "Parmi les initiatives réalisées, le Manakin Eco-Trail se distingue, ainsi que diverses actions d'entretien et d'amélioration des espaces communautaires.",
        quienes_photo_credit: "Photo : Paraíso Tropical Caño Negro",
        quienes_sloth_caption: "Paresseux à gorge brune (<em>Bradypus variegatus</em>)",

        quienes_fact1_title: "Développement communautaire",
        quienes_fact1_text: "Des initiatives et actions au bénéfice direct de la communauté de Caño Negro.",
        quienes_fact2_title: "Tourisme",
        quienes_fact2_text: "Promotion de projets touristiques comme le Manakin Eco-Trail.",
        quienes_fact3_title: "Infrastructure",
        quienes_fact3_text: "Entretien et amélioration des espaces et des infrastructures communautaires.",
        quienes_fact4_title: "Sport",
        quienes_fact4_text: "Soutien aux espaces et projets liés au sport et aux loisirs.",
        quienes_fact5_title: "Participation citoyenne",
        quienes_fact5_text: "Bénévolat et espaces de participation pour les voisins.",
        quienes_fact6_title: "Travail collaboratif",
        quienes_fact6_text: "Partenariats avec des institutions, des universités, des organisations et des entreprises.",

        vol_label: "Bénévolat",
        vol_title: "Faites partie du changement",
        vol_subtitle: "La participation des habitants est essentielle pour développer des activités et des initiatives. Voici quelques-unes des façons dont la communauté s'est impliquée.",

        vol_card1_title: "Charity CR",
        vol_card1_desc: "Activités pour les enfants et les familles de la communauté, réalisées avec Charity CR.",
        vol_card2_title: "Journées de nettoyage",
        vol_card2_desc: "Nettoyage du Parc et du Campo Ferial avec des bénévoles de la communauté.",
        vol_card3_title: "Collaboration avec des organisations",
        vol_card3_desc: "Travail conjoint avec différentes organisations et institutions au bénéfice de Caño Negro.",
        vol_card4_title: "Participation communautaire",
        vol_card4_desc: "Participation à des activités, des formations et des initiatives liées à des projets communautaires.",

        vol_note: "Le plan de travail prévoit le développement d'un Programme de Bénévolat pour renforcer la participation communautaire.",

        proy_label: "Notre travail",
        proy_title: "Ce que nous avons construit",
        proy_subtitle: "Voici quelques-unes des actions que nous avons menées aux côtés de la communauté, des institutions et des organisations partenaires.",

        proy1_title: "Manakin Eco-Trail",
        proy1_desc: "Développement d'une initiative touristique aux côtés d'institutions, d'organisations et d'universités, avec des travaux sur le sentier et le Centre de Développement Touristique et Entrepreneurial.",
        proy2_title: "Amélioration des espaces communautaires",
        proy2_desc: "Entretien, nettoyage, sécurité et amélioration des infrastructures dans différents espaces de la communauté.",
        proy3_title: "Campo Ferial",
        proy3_desc: "Travaux d'entretien et d'amélioration du Campo Ferial.",
        proy4_title: "Infrastructure",
        proy4_desc: "Améliorations liées à l'électricité, à la plomberie et à différents espaces communautaires du sentier.",
        proy5_title: "Sécurité communautaire",
        proy5_desc: "Travail conjoint avec la Force Publique et mise en place de Tables de Sécurité.",
        proy6_title: "Partenariats et collaboration",
        proy6_desc: "Travail conjoint avec des universités, des institutions, des organisations et des entreprises partenaires.",

        badge_completado: "Terminé",
        badge_proyectado: "Planifié",

        futuro_label: "Vers l'avenir",
        futuro_title: "Nous continuons à construire",
        futuro_subtitle: "Le Plan de Travail prévoit de nouvelles initiatives pour continuer à promouvoir le développement de Caño Negro.",

        fut1_title: "Tourisme et développement",
        fut1_item1: "Développement de projets touristiques.",
        fut1_item2: "Centre de Formation Touristique et Entrepreneuriale.",
        fut1_item3: "Renforcement des espaces liés au tourisme.",

        fut2_title: "Sport et loisirs",
        fut2_item1: "Amélioration du terrain de football : vestiaires, clôture et gradins.",
        fut2_item2: "Construction d'un espace polyvalent pour le sport.",
        fut2_item3: "Amélioration des espaces sportifs et récréatifs.",

        fut3_title: "Infrastructure communautaire",
        fut3_item1: "Rénovation et équipement de la salle communale.",
        fut3_item2: "Entretien et construction d'ouvrages communaux.",
        fut3_item3: "Construction et équipement d'une cuisine communale.",
        fut3_item4: "Améliorations du réseau routier cantonal et du système d'égouts.",

        fut4_title: "Équipement et ressources",
        fut4_item1: "Outils et équipement.",
        fut4_item2: "Équipement technologique et sonore.",
        fut4_item3: "Fournitures, équipement et mobilier de bureau.",
        fut4_item4: "Matériel de premiers secours et éléments de sécurité.",

        fut5_title: "Participation communautaire",
        fut5_item1: "Programme de Bénévolat.",
        fut5_item2: "Réunions et formations.",
        fut5_item3: "Activités de participation et de collaboration communautaire.",

        closing_tag: "ADI Caño Negro",
        closing_title: "« Quand une communauté travaille unie, elle ne construit pas seulement des projets, elle construit un avenir. »",
        closing_desc: "Que vous soyez voisin, visiteur ou partenaire institutionnel, il y a une place pour vous dans les projets de l'ADI Caño Negro.",

        help_title: "Comment pouvons-nous vous aider ?",

        faq_q1: "🤝 Qu'est-ce que l'ADI Caño Negro ?",
        faq_a1: "C'est l'Association de Développement Intégral de Caño Negro, une organisation communautaire à but non lucratif.",
        faq_q2: "🙋 Comment puis-je devenir bénévole ?",
        faq_a2: "Vous pouvez nous écrire sur WhatsApp ou par e-mail et nous vous indiquerons les façons actuelles de participer.",
        faq_q3: "📅 Quand l'ADI se réunit-elle ?",
        faq_a3: "Les réunions et activités sont coordonnées selon chaque projet ; contactez-nous pour plus d'informations.",
        faq_q4: "📍 Où se trouve Caño Negro ?",
        faq_a4: "Il est situé à Los Chiles, Alajuela, Costa Rica, près de la frontière avec le Nicaragua.",
        faq_q5: "🚗 Comment y accéder ?",
        faq_a5: "Vous pouvez y accéder par la Route 138 depuis Upala ou Los Chiles. Utilisez le bouton de localisation pour voir l'itinéraire.",

        chat_tab: "À propos de Caño Negro",

        footer_about: "Association de Développement Intégral de Caño Negro, œuvrant aux côtés de la communauté pour le développement touristique, sportif, entrepreneurial et communautaire.",
        footer_links_title: "Liens rapides",
        footer_contact_title: "Contact",
        footer_address: "Caño Negro, Los Chiles, Alajuela, Costa Rica",
        footer_social_title: "Suivez-nous",
        footer_text: "© 2026 ADI Caño Negro - Tous droits réservés"
    }
};
